# Numpy

In [1]:
np = [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]

In [2]:
flotY = [np, np, np]
flotY

[[1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [3]:
flotY[0]

[1.0, 10.4, 3.2, 5.1, 7.5, 2.7]

In [5]:
flotV = [np, np, np]

In [6]:
flotV[0]='Python' 
flotV

['Python', [1.0, 10.4, 3.2, 5.1, 7.5, 2.7], [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [7]:
import numpy as np

In [8]:
a = np.array([1, 2.5, 4.0, 5.5, 7.0])
a[3:] 

array([5.5, 7. ])

In [9]:
a.sum()

20.0

In [10]:
a.std()

2.1213203435596424

In [11]:
a.cumsum()

array([ 1. ,  3.5,  7.5, 13. , 20. ])

In [12]:
print(np.sqrt(a))

[1.         1.58113883 2.         2.34520788 2.64575131]


In [18]:
values = np.zeros((2,3), dtype='i')
values

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [15]:
b = np.array([a, a**2])
b

array([[ 1.  ,  2.5 ,  4.  ,  5.5 ,  7.  ],
       [ 1.  ,  6.25, 16.  , 30.25, 49.  ]])

In [16]:
b.sum(axis=0)

array([ 2.  ,  8.75, 20.  , 35.75, 56.  ])

In [17]:
b.sum(axis=1)

array([ 20. , 102.5])

In [20]:
values = np.zeros((2,3), dtype='i')
values

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [21]:
import pandas as pd 
import numpy as np  

In [22]:
pandas_series = pd.Series([3000, 3200, 2700],
                          index = ['2016-11-10','2016-11-11','2016-11-12'])

In [23]:
pandas_series

2016-11-10    3000
2016-11-11    3200
2016-11-12    2700
dtype: int64

In [24]:
pandas_series[1:]

2016-11-11    3200
2016-11-12    2700
dtype: int64

In [25]:
df = pd.DataFrame([100, 150, 200, 250, 300], columns=['numbers'], index=['a','b','c','d','e'] )
df

numbers
a      100
b      150
c      200
d      250
e      300

In [27]:
df.index
df.columns

Index(['numbers'], dtype='object')